### ISSUE TITLE
(Request) how to mining SEQ Coin.

### ISSUE THREAD

**Issue by RagaSonic** [duality-solutions/Sequence#105]
Sorry for request but I'm total noob.
I know how to mine LTC by ccminer.
But I don't know how to work SEQ Coin?

(Pool Mining? Solo Mining? Another?)

Please help.

My current config is W10 64bit + 16Gb of Ram and Nvidia GTX 1060 6Gb

**Comment by spencerlievens** [comment]
Sequence is only PoS mineable, however, Dynamic is PoW mineable.
