### ISSUE TITLE
Stake received 1.999 instead of 2.000

### ISSUE THREAD

**Issue by AmirAbrams** [duality-solutions/Sequence#106]
### Describe the issue
The stake reward is sometimes 1.999 instead of 2.000.  
### Steps to reproduce
Unable to reproduce the issue but if you receive enough stake rewards, you will see it happen.
See tx: 3e6e9d58b662bbf1900b935428f75cbdb9c9fc85b011becd17e38593be9f4da2
### Expected behavior
The stake reward should always be 2.000.

**Comment by Duality-CDOO** [comment]
Fee indiscrepency in the codebase.

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Sequence/blob/v1.2-WIP/src/wallet/wallet.cpp#L2674 should not have "- nMinFee".

Nor should line 2671.

This will need to be a fork.

**Comment by Duality-CDOO** [comment]
https://github.com/duality-solutions/Sequence/commit/b833e6f937c2d7f77a63ea7925b4f4d9bbfe7aaf

**Comment by Duality-CDOO** [comment]
Will change the check to be for block.nversion instead and up the version to 3

**Comment by Duality-CDOO** [comment]
Fixed in 1.3
