### ISSUE TITLE
Gitian Build System VM Image for Sequence

### ISSUE THREAD

**Issue by spencerlievens** [duality-solutions/Sequence#11]
### Describe the issue

We need to build statically linked signed binaries for all platforms including Windows 32/64, Mac OS X, Linux, Pi, Arm, Android, etc.. Travis Ci needs to be integrated with our Gitian process so we can confirm we don't break any supported platforms when we upgrade our code base .  The same Gitian VM should work for Dynamic.

All core developers will need a GPG (aka PGP) key to build signed binaries. I use Kleopatra to create my GPG key for development.

**Comment by quantumgravity444** [comment]
I have this almost completed. Will update soon.
