### ISSUE TITLE
Building Sequence with --with-gui=auto fails

### ISSUE THREAD

**Issue by BloodyNora** [duality-solutions/Sequence#118]
### Describe the issue
When building Sequence on a recent debian9 with all updates etcpp, the build fails 
`Makefile:5432: recipe for target 'qt/qt_libsequenceqt_a-stakereportdialog.o' failed`
### Steps to reproduce
1. `git clone https://github.com/duality-solutions/Sequence`
2. `cd Sequence`
3. `./autogen.sh`
4. `./configure --with-incompatible-bdb --with-gui=auto`
5. `make`

### Expected behavior
Build completes.

### Actual behavior
Build fails:
`In file included from qt/stakereportdialog.cpp:8:0:
./qt/forms/ui_stakereportdialog.h: In member function ‘void Ui_StakeReportDialog::setupUi(QDialog*)’:
./qt/forms/ui_stakereportdialog.h:320:27: error: ‘class QTableWidget’ has no member named ‘setSizeAdjustPolicy’; did you mean ‘setSizePolicy’?
         StakeReportTable->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
                           ^~~~~~~~~~~~~~~~~~~
./qt/forms/ui_stakereportdialog.h:320:47: error: ‘AdjustIgnored’ is not a member of ‘QAbstractScrollArea’
         StakeReportTable->setSizeAdjustPolicy(QAbstractScrollArea::AdjustIgnored);
                                               ^~~~~~~~~~~~~~~~~~~
Makefile:5432: recipe for target 'qt/qt_libsequenceqt_a-stakereportdialog.o' failed
make[2]: *** [qt/qt_libsequenceqt_a-stakereportdialog.o] Error 1
`
### What platform are you using (Linux, Windows, Mac)
`# uname -a`
`Linux x220 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`
`# cat /etc/debian_version `
`9.4`

**Comment by Duality-CDOO** [comment]
Could you please testbuild the branch called "buildtest".

**Comment by Duality-CDOO** [comment]
Sequence must be built with qt5.
