### ISSUE TITLE
[RPC] GetInfo command testnet value incorrect

### ISSUE THREAD

**Issue by spencerlievens** [duality-solutions/Sequence#12]
### Describe the issue
While using testnet, the `getinfo` command returns `"testnet" = false`.
#### Steps to reproduce
1. In silk.conf, add `testnet=1`
2. Run the wallet (Qt or Daemon).  It should be in testnet mode.
3. Execute the `getinfo` command from the console.
#### Expected behavior
When not using the main network, the getinfo JSON should return `"testnet" = true`.
#### Actual behavior
It always returns `"testnet" = false`.
#### Screenshots
![silk-getinfo-testnet-bug](http://i.imgur.com/Ya88hxp.png)
#### What platform are you using (Linux, Windows, Mac)
Ubuntu Linux 16.04 64 bit.

**Comment by SCDeveloper** [comment]
Is this issue fixed in v1.2.0.0?
