### ISSUE TITLE
staking=0 in conf wallet is staking still

### ISSUE THREAD

**Issue by ultra-pool** [duality-solutions/Sequence#139]
Good evening. 

I have staking=0 in my wallet conf file and noticed that the daemon is still staking.

"enabled": false,
  "staking": true,
  "errors": "",

Any work around other then encrypting the wallet to make it stop.

**Comment by CryptoCanary** [comment]
Try stakegen=0

Reference: https://github.com/duality-solutions/Sequence/blob/3d307a40ae47b94c251b4fd94585156ea5afd542/src/init.cpp#L1489

**Comment by AmirAbrams** [comment]
@CryptoCanary, you beat me to it.  Thanks for your help.

**Comment by ultra-pool** [comment]
Thank you for reply. 

Im used to using staking=0. Ill try this and close it works for me.

**Comment by ultra-pool** [comment]
Seems to be working. Thank you.
