### ISSUE TITLE
qt menu bar is unuseable ubuntu16

### ISSUE THREAD

**Issue by bumbacoin** [duality-solutions/Sequence#143]
### Describe the issue

TOTAL USER ERROR.

### Describe the issue
under ubuntu 16, Qt Menu Bar is missing
### Steps to reproduce
1.  open qt in ubuntu 16
2.  click on menu 

### Expected behavior
menu should be populated and useable

### Actual behavior
menu bar is empty 

### Screenshots
![sequence-fail-menu](https://user-images.githubusercontent.com/7548445/61168212-2ca4be80-a57d-11e9-873b-8c8a912ebe2e.png)

### What platform are you using (Linux, Windows, Mac)
ubuntu 16

**Comment by bumbacoin** [comment]
i notice the menu bar is available in ubuntu 18

![sequence-ok-menu](https://user-images.githubusercontent.com/7548445/61168864-e05e7c00-a586-11e9-97c1-021fdbb1c41e.png)

**Comment by Duality-CDOO** [comment]
In Ubuntu 16, are you sure the menu isn't located in the OS main bar at the top? Same location as the clock, but to the left.

**Comment by bumbacoin** [comment]
well colour me embarrassed,
i swear i checked that before :P 

thanks, it's all good now
