### ISSUE TITLE
Problem with ./autogen and make

### ISSUE THREAD

**Issue by beralt85** [duality-solutions/Sequence#15]
### Describe the issue
Build fails with:
`Makefile.am:231: library has 'libsilk_zmq_a' as canonical name (possible typo)`
`./autogen.sh` gives warning/error:
```src/Makefile.am:479: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here
src/Makefile.am:231: warning: variable 'libsilk_zmq_a_SOURCES' is defined but no program or
src/Makefile.am:231: library has 'libsilk_zmq_a' as canonical name (possible typo)
```

### Steps to reproduce
1. get latest source
2. `./autogen.sh`
3. `make`

### Expected behavior
Should build

### Actual behavior
Doesn't build

### What platform are you using (Linux, Windows, Mac)
Arch, Raspbian

**Comment by beralt85** [comment]
I think it is this commit that changed that: https://github.com/SilkNetwork/Silk-Core/commit/e8fd6119b986c9b13f15e54b547bf1823a126190#diff-480477e89f9b6ddafb30c4383dcdd705

**Comment by AmirAbrams** [comment]
Do you have ZMQ and libevent installed?   ZMQ should be optional but I don't think it builds without it right now.  We need to update our documentation to include those libraries.

**Comment by beralt85** [comment]
ZMQ is installed, also libevent: package libevent-dev on raspbian, package libevent on arch.

**Comment by quantumgravity444** [comment]
I'm getting a similar error when I try to build from master:

`In file included from init.cpp:49:0:
zmq/zmqnotificationinterface.h:9:36: fatal error: validationinterface.h: No such file or directory
compilation terminated.
Makefile:3367: recipe for target 'libsilk_server_a-init.o' failed
`

**Comment by GregoryBetz** [comment]
Fixing it now.

**Comment by quantumgravity444** [comment]
I added the zmq deps and tried to build and ran into a bunch more errors. This still needs a ton of work or ZMQ should be removed.

For now, it builds with ./configure --disable-zmq, but that is just annoying haha
