### ISSUE TITLE
Fix Unit Tests

### ISSUE THREAD

**Issue by spencerlievens** [duality-solutions/Sequence#2]
### Describe the issue

Fix unit tests.  Build broke when we updated leveldb.
src/makefile.am

```
# TODO (Amir) put back unit tests
#if ENABLE_TESTS
#include Makefile.test.include
#endif

#if ENABLE_QT_TESTS
#include Makefile.qttest.include
#endif
```

**Comment by SCDeveloper** [comment]
https://github.com/SilkNetwork/Silk-Core/commit/ff909ef2ec441ddc953a2a9c174f96be1012c804

**Comment by SCDeveloper** [comment]
Fixed in above commit
