### ISSUE TITLE
ZMQ is not properly added to the codebase. Many Errors and missing files.

### ISSUE THREAD

**Issue by quantumgravity444** [duality-solutions/Sequence#20]
### Describe the issue
Unless the --disable-zmq is added to your configuration command, the code is broken and the following error is given;

```
In file included from init.cpp:49:0:
zmq/zmqnotificationinterface.h:9:33: fatal error: validationinterface.h: No such file or directory
compilation terminated.
```
When that include is commented out the following compilation error is given:

`make[2]: *** No rule to make target 'libsilk_zmq.a', needed by 'silkd'.  Stop.`

After fixing that issue I recieved about 20 more compilation errors related to ZMQ files.

I'm not sure how this made it into master to begin with, but it either needs to be completely reverted or fixed. 
### Steps to reproduce
1. Follow the normal build instructions.

### What platform are you using (Linux, Windows, Mac)

Ubuntu 16

**Comment by quantumgravity444** [comment]
I've updated the issue with more information.

**Comment by quantumgravity444** [comment]
To fully implement ZMQ properly so it can actually function there are several or more files added and upgrades that should have been completed first after researching bitcoin's development history.

**Comment by quantumgravity444** [comment]
The original PR can be found here: https://github.com/duality-solutions/Sequence/pull/64

I was surprised to see that it passed Travis, but after looking at the Travis output I was even more surprised to see that it somehow did not use the newly changed configure and makefiles. It is very strange.

**Comment by ghost** [comment]
Thank you for removing ZMQ, I'll rework the branch and fix it
