### ISSUE TITLE
Add the ability to remove Watch-Only Addresses

### ISSUE THREAD

**Issue by spencerlievens** [duality-solutions/Sequence#4]
### Describe the issue

Import Address allows for the addition of a watch-only address but there is no way to remove it.
### Steps to reproduce
1. ImportAddress in RPC/Debug Console
2. Go to RPC/Debug and look through commands.
3. Feel frustrated that you cannot remove it.
### Expected behavior

Watch-Only Address has a function for removal.
### Actual behavior

Frustration
### What platform are you using (Linux, Windows, Mac)

Source-Code (Non-Platform Related)

**Comment by spencerlievens** [comment]
https://github.com/bitcoin/bitcoin/pull/5525/commits/c6844c901ac349186ddbc1a17990dc0b068efb9a

**Comment by quantumgravity444** [comment]
I just found that commit as well and I've implemented it. PR coming up.
